# Generated by Django 4.1.2 on 2022-10-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0003_carros_ano_fabricacao_carros_placa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carros',
            old_name='Ano_fabricacao',
            new_name='Ano_fabricação',
        ),
        migrations.AddField(
            model_name='carros',
            name='Modelo',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carros',
            name='Versão',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carros',
            name='chassi',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carros',
            name='cor',
            field=models.CharField(default=2022, max_length=50),
            preserve_default=False,
        ),
    ]
