# Generated by Django 4.1.2 on 2022-10-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0004_rename_ano_fabricacao_carros_ano_fabricação_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carros',
            name='obs_carro',
            field=models.TextField(default=2022),
            preserve_default=False,
        ),
    ]
