# Generated by Django 4.1.2 on 2022-10-30 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_clientes_obs_alter_clientes_sexo'),
        ('carros', '0005_carros_obs_carro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordens_de_Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.CharField(max_length=50)),
                ('data_entrada', models.CharField(max_length=50)),
                ('data_saida', models.CharField(max_length=50)),
                ('km', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('Ano_fabricação', models.CharField(max_length=50)),
                ('situacao', models.CharField(max_length=50)),
                ('localizacao', models.CharField(max_length=50)),
                ('reboque', models.CharField(max_length=50)),
                ('obs_int', models.TextField()),
                ('obs_cliente', models.TextField()),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carros.carros')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
            ],
        ),
    ]
