# Generated by Django 4.1.2 on 2022-10-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='Sexo',
            field=models.CharField(choices=[('F', 'Masculino'), ('M', 'Feminino')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(default=2022, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='endereço',
            field=models.CharField(default=22, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='telefone',
            field=models.CharField(default=2022, max_length=100),
            preserve_default=False,
        ),
    ]
